farm_arable.settings:
  type: config_object
  label: 'Arable Settings'
  mapping:
    default_api_key:
      type: string
      label: 'Default Arable API Key'
      description: 'The default API key used when creating Arable sensor assets.'
